server:
  port: 8080

spring:
  ## 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  ## freemarker模板
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

  mvc:
    static-path-pattern: /**

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
