server:
  port: 8080

spring:
  ## 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.230.125:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Guan123,.

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

logging:
  config: classpath:logback/logback-dev.xml