------------------------------------
---表名：DEMO_DEPARTMENT（部门信息）
------------------------------------
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME,DELETED) VALUES(0,'总行',0);
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME,DELETED) VALUES(1,'杭州分行',0);
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME,DELETED) VALUES(2,'西湖支行',0);
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME,DELETED) VALUES(2,'滨江支行',0);
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME,DELETED) VALUES(1,'北京分行',0);


------------------------------------
---表名：DEMO_PERSON（人员信息）
------------------------------------
INSERT INTO DEMO_PERSON(NAME,ACCOUNT,PASSDORD,DEPARTMENT_ID,AGE,SEX,TEL,EMAIL,ADDRESS,DELETED) VALUES('张三','zhangsan','123456',1,34,'1','17877650973','zhangsan@163.com','西湖',0);
INSERT INTO DEMO_PERSON(NAME,ACCOUNT,PASSDORD,DEPARTMENT_ID,AGE,SEX,TEL,EMAIL,ADDRESS,DELETED) VALUES('李四','lisi','123456',2,24,'1','17863650973','lisi@163.com','青海湖',0);
INSERT INTO DEMO_PERSON(NAME,ACCOUNT,PASSDORD,DEPARTMENT_ID,AGE,SEX,TEL,EMAIL,ADDRESS,DELETED) VALUES('王五','wangwu','123456',3,26,'1','17876750973','wangwu@163.com','湘湖',0);
INSERT INTO DEMO_PERSON(NAME,ACCOUNT,PASSDORD,DEPARTMENT_ID,AGE,SEX,TEL,EMAIL,ADDRESS,DELETED) VALUES('赵六','zhaoliu','123456',4,30,'1','17872350973','zhaoliu@163.com','洞庭湖',0);
INSERT INTO DEMO_PERSON(NAME,ACCOUNT,PASSDORD,DEPARTMENT_ID,AGE,SEX,TEL,EMAIL,ADDRESS,DELETED) VALUES('小七','xiaoqi','123456',5,23,'0','17877698973','xiaoqi@163.com','鄱阳湖',0);

