------------------------------------
---表名：DEMO_DEPARTMENT（部门信息）
------------------------------------
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME) VALUES(0,'总行');
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME) VALUES(1,'杭州分行');
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME) VALUES(2,'西湖支行');
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME) VALUES(2,'滨江支行');
INSERT INTO DEMO_DEPARTMENT(PARENT_ID,NAME) VALUES(1,'北京分行');


------------------------------------
---表名：DEMO_PERSON（人员信息）
------------------------------------
INSERT INTO DEMO_PERSON(NAME,DEPARTMENT_ID,AGE,SEX,TEL,ADDRESS) VALUES('张三',1,34,'1','17877650973','西湖');
INSERT INTO DEMO_PERSON(NAME,DEPARTMENT_ID,AGE,SEX,TEL,ADDRESS) VALUES('李四',2,24,'1','17863650973','青海湖');
INSERT INTO DEMO_PERSON(NAME,DEPARTMENT_ID,AGE,SEX,TEL,ADDRESS) VALUES('王五',3,26,'1','17876750973','湘湖');
INSERT INTO DEMO_PERSON(NAME,DEPARTMENT_ID,AGE,SEX,TEL,ADDRESS) VALUES('赵六',4,30,'1','17872350973','洞庭湖');
INSERT INTO DEMO_PERSON(NAME,DEPARTMENT_ID,AGE,SEX,TEL,ADDRESS) VALUES('小七',5,23,'0','17877698973','鄱阳湖');

