------------------------------------
---表名：DEMO_PERSON（人员信息）
------------------------------------
CREATE TABLE DEMO_PERSON
(
	ID         		VARCHAR2(32) NOT NULL,
	NAME       		VARCHAR2(10),
	DEPARTMENT_ID 	VARCHAR2(32),
	AGE        		VARCHAR2(3),
	SEX        		VARCHAR2(1),
	TEL        		VARCHAR2(20),
	ADDRESS    		VARCHAR2(20),
	PRIMARY_KEY ('ID')
);
COMMENT ON TABLE DEMO_PERSON IS '人员信息';
COMMENT ON COLUMN DEMO_PERSON.ID IS '人员编号';
COMMENT ON COLUMN DEMO_PERSON.NAME IS '姓名';
COMMENT ON COLUMN DEMO_PERSON.DEPARTMENT_ID IS '部门编号';
COMMENT ON COLUMN DEMO_PERSON.AGE IS '年龄';
COMMENT ON COLUMN DEMO_PERSON.SEX IS '性别（0：女，1：男）';
COMMENT ON COLUMN DEMO_PERSON.TEL IS '电话';
COMMENT ON COLUMN DEMO_PERSON.ADDRESS IS '地址';

------------------------------------
---表名：DEMO_DEPARTMENT（部门信息）
------------------------------------
CREATE TABLE DEMO_DEPARTMENT
(
	ID         		VARCHAR2(32) NOT NULL,
	PARENT_ID       VARCHAR2(32) NOT NULL,
	NAME       		VARCHAR2(10),
	PRIMARY_KEY (ID)
);
COMMENT ON TABLE DEMO_DEPARTMENT IS '部门信息';
COMMENT ON COLUMN DEMO_DEPARTMENT.ID IS '部门编号';
COMMENT ON COLUMN DEMO_DEPARTMENT.AGE IS '父级编号';
COMMENT ON COLUMN DEMO_DEPARTMENT.NAME IS '部门名称';